import type { Metadata } from "next";
import "../globals.css";
import { ReactNode } from "react";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
      </Head>
      <html lang="ko" className="bg-slate-100">
        <body
          className={`relative mx-auto flex h-full min-h-screen w-screen flex-col bg-white antialiased xl:max-w-[1280px]`}
        >
          <div className="relative mx-auto flex size-full flex-1 flex-col">{children}</div>
        </body>
      </html>
    </>
  );
}
